name: e2e

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */9 * * *'
  workflow_dispatch:

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
      with:
        max_attempts: 3
        timeout_minutes: 5
        retry_on: error
        command: |
          cd ./e2e
          python -m pip install wheel
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
    - name: Preapre tests
      run: |
        launchable record build --name ${GITHUB_RUN_ID}
      working-directory: ./e2e
    - name: Run tests
      run: |
        python runner.py
      working-directory: ./e2e
    - name: slack notify
      if: failure()
      uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8 # v2.2.1
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON_EMOJI: ":rotating_light:"
        SLACK_TITLE: " :boom: nose-launchable e2e test failed :boom:"
        SLACK_MESSAGE: '<https://github.com/launchableinc/nose-launchable/actions/|Please check e2e test result>'
        SLACK_COLOR: "#ff0000"
